---
title: "ShinyApp"
author: "141B Group"
date: "3/18/2020"
output: html_document
---
```{r}
library(shiny)
library(dplyr)
library(tidyverse)
```

```{r}
agedf<-read_csv("agedf.csv") %>%
  mutate(category_choice = "age") %>%
  rename("category"="age")
edudf<-read_csv("edudf.csv") %>% 
  mutate(category_choice = "education") %>%
  rename("category"="education") 
genderdf<-read_csv("genderdf.csv")%>% 
  mutate(category_choice = "gender") %>%
  rename("category"="gender") 
incomedf<-read_csv("incomedf.csv")%>% 
  mutate(category_choice = "income") %>%
  rename("category"="income") 
racedf<-read_csv("racedf.csv")%>% 
  mutate(category_choice = "race") %>%
  rename("category"="race") 
regiondf<-read_csv("regiondf.csv")%>% 
  mutate(category_choice = "region") %>%
  rename("category"="region") 
full_data <- rbind(agedf,edudf,genderdf,incomedf,racedf,regiondf) %>% 
  mutate(question = case_when(
    question==1 ~ "How closely are you following the news about coronavirus?",
    question==2 ~ "Do you approve or disapprove of Donald Trump’s handling of the coronavirus outbreak?",
    question==3 ~ "How concerned are you about a coronavirus epidemic here in the United States?",
    question==4 ~ "How would you describe the way most Americans are thinking about coronavirus?",
    TRUE~"Taking into consideration both your risk of contracting it and the seriousness of the illness, how worried are you personally about experiencing coronavirus?"))
```

```{r}
ui <- fluidPage(
  #create a layout
  sidebarLayout(
    #sidebar area
  sidebarPanel(
    #user select their interested from the drop down menu
    selectInput(inputId = "question",
              label = "Select your interested question: ",
              choices = unique(full_data$question), 
              selected = NULL),
  #user select their interested category from the drop down menu
  selectInput(inputId = "category",
              label = "Select your interested catergory: ",
              choices = unique(full_data$category_choice),
              selected = NULL),
  #user select their interested category from the drop down menu
  selectInput(inputId = "demographic",
              label = "Select your interested demographic: ",
              choices = unique(full_data$category),
              selected = NULL)),
  #main area
  mainPanel(plotOutput("selected_graph")),
    #position of sidebar
    position = c("left"),
    #fixed
    fluid = FALSE))

  server <- function(input, output){

  #filter out the needed data
  full_data2 <- reactive({
    filter(full_data, question==input$question & category_choice==input$category & category==input$demographic)})
  
  #output of ggplot
  output$selected_graph <- renderPlot({
    ggplot(data=full_data2(),aes(x=week,y=percent, group = response))+
      geom_point()+geom_line(aes(color=response))+
      ggtitle(paste("Change in the percentage of",input$demographic,"in",input$category,"toward the answer of ' ",input$question,"' "))})}
  
shinyApp(ui = ui, server = server)

```
